<a href="https://colab.research.google.com/github/Azaharuddin786/MY-FIRST-PROJECT-786/blob/main/CIFAR_10_data_sets_solved.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,BatchNormalization,Activation
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.constraints import maxnorm
from keras.utils import np_utils

In [2]:
seed=21

In [3]:
from keras.datasets import cifar10

In [4]:
(x_train,y_train),(x_test,y_test) = cifar10.load_data()

170508288/170498071 [==============================] - 3s 0us/step


In [5]:
print(x_train[0])

[[[ 59  62  63]
  [ 43  46  45]
  [ 50  48  43]
  ...
  [158 132 108]
  [152 125 102]
  [148 124 103]]

 [[ 16  20  20]
  [  0   0   0]
  [ 18   8   0]
  ...
  [123  88  55]
  [119  83  50]
  [122  87  57]]

 [[ 25  24  21]
  [ 16   7   0]
  [ 49  27   8]
  ...
  [118  84  50]
  [120  84  50]
  [109  73  42]]

 ...

 [[208 170  96]
  [201 153  34]
  [198 161  26]
  ...
  [160 133  70]
  [ 56  31   7]
  [ 53  34  20]]

 [[180 139  96]
  [173 123  42]
  [186 144  30]
  ...
  [184 148  94]
  [ 97  62  34]
  [ 83  53  34]]

 [[177 144 116]
  [168 129  94]
  [179 142  87]
  ...
  [216 184 140]
  [151 118  84]
  [123  92  72]]]


In [6]:
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train = x_train/255
x_test = x_test/255

In [7]:
y_train = np_utils.to_categorical(y_train)
y_test = np_utils.to_categorical(y_test)
class_num = y_test.shape[1]

In [8]:
model = Sequential()

In [9]:
model.add(Conv2D(32, (3,3), input_shape = x_train.shape[1:], padding='same'))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Conv2D(64, (3,3), padding= 'same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Conv2D(64, (3,3), padding= 'same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(BatchNormalization())

model.add(Conv2D(128, (3,3), padding= 'same'))
model.add(Activation('relu'))
model.add(BatchNormalization())


model.add(Flatten())


model.add(Dense(128,kernel_constraint=maxnorm(3,)))
model.add(Activation('relu'))
model.add(Dropout(0.2))
model.add(BatchNormalization())

model.add(Dense(256,kernel_constraint=maxnorm(3,)))
model.add(Activation('relu'))
model.add(BatchNormalization())

model.add(Dense(class_num))
model.add(Activation('softmax'))

In [10]:
epochs =25
optimizer='adam'

In [11]:


model.compile(loss= 'CategoricalCrossentropy', optimizer=optimizer, metrics =['accuracy'])

In [12]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 32, 32, 32)        896       
                                                                 
 activation (Activation)     (None, 32, 32, 32)        0         
                                                                 
 dropout (Dropout)           (None, 32, 32, 32)        0         
                                                                 
 batch_normalization (BatchN  (None, 32, 32, 32)       128       
 ormalization)                                                   
                                                                 
 conv2d_1 (Conv2D)           (None, 32, 32, 64)        18496     
                                                                 
 activation_1 (Activation)   (None, 32, 32, 64)        0         
                                                        

In [13]:
numpy.random.seed(seed)
model.fit(x_train,y_train, validation_data=(x_test,y_test), epochs=epochs, batch_size=64)

Epoch 1/25
782/782 [==============================] - 32s 25ms/step - loss: 1.3926 - accuracy: 0.5045 - val_loss: 1.4892 - val_accuracy: 0.5188
Epoch 2/25
782/782 [==============================] - 19s 24ms/step - loss: 0.9278 - accuracy: 0.6705 - val_loss: 0.7980 - val_accuracy: 0.7217
Epoch 3/25
782/782 [==============================] - 19s 24ms/step - loss: 0.7496 - accuracy: 0.7359 - val_loss: 1.0145 - val_accuracy: 0.6624
Epoch 4/25
782/782 [==============================] - 19s 24ms/step - loss: 0.6572 - accuracy: 0.7694 - val_loss: 0.7078 - val_accuracy: 0.7601
Epoch 5/25
782/782 [==============================] - 18s 23ms/step - loss: 0.5847 - accuracy: 0.7971 - val_loss: 0.6843 - val_accuracy: 0.7654
Epoch 6/25
782/782 [==============================] - 18s 23ms/step - loss: 0.5286 - accuracy: 0.8128 - val_loss: 0.6704 - val_accuracy: 0.7711
Epoch 7/25
782/782 [==============================] - 18s 23ms/step - loss: 0.4804 - accuracy: 0.8310 - val_loss: 0.6346 - val_accuracy:

In [15]:
scores = model.evaluate(x_test,y_test, verbose=0)
print("accuracy: %.2f%%" % (scores[1]*100))

accuracy: 79.33%
